export const slides = [
  { title: "Game time. Bring the heat.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img1.jpg" },
  { title: "Power serve. Sharp focus.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img2.jpg" },
  { title: "Fast feet. Clean shots.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img3.jpg" },
  { title: "Own the court. Every point.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img4.jpg" },
  { title: "Energy up. Play strong.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img5.jpg" },
  { title: "Perfect form. Pure padel.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img6.jpg" },
  { title: "Speed meets control.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img7.jpg" },
  { title: "Strike clean. Move fast.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img8.jpg" },
  { title: "Sharp hits. Zero fear.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img9.jpg" },
  { title: "Focus locked. Game on.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img10.jpg" },
  { title: "Fluid motion. Strong finish.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img11.jpg" },
  { title: "Train smart. Play harder.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img12.jpg" },
  { title: "Instant reaction. Full power.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img13.jpg" },
  { title: "No limits. Just play.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img14.jpg" },
  { title: "Strike fast. Think fast.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img15.jpg" },
  { title: "Pure rhythm. Pure drive.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img16.jpg" },
  { title: "Every swing counts.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img17.jpg" },
  { title: "Push harder. Level up.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img18.jpg" },
  { title: "Stay sharp. Stay fierce.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img19.jpg" },
  { title: "Point by point. Win big.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img20.jpg" },
  { title: "Chase the rally. Own it.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img21.jpg" },
  { title: "Precision wins.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img22.jpg" },
  { title: "Elite focus. Elite energy.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img23.jpg" },
  { title: "Light swing. Heavy impact.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img24.jpg" },
  { title: "Play bold. Play clean.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img25.jpg" },
  { title: "Teamwork makes the point.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img26.jpg" },
  { title: "Quick read. Big return.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img27.jpg" },
  { title: "Pro movement. Pro mindset.", image: "https://raw.githubusercontent.com/FatalFriction/lapalma-padelclub/master/public/slider/img28.jpg" },
];
