export const slides = [
  { title: "Game time. Bring the heat.", image: "/slider/img1.webp" },
  { title: "Power serve. Sharp focus.", image: "/slider/img2.webp" },
  { title: "Fast feet. Clean shots.", image: "/slider/img3.webp" },
  { title: "Own the court. Every point.", image: "/slider/img4.webp" },
  { title: "Energy up. Play strong.", image: "/slider/img5.webp" },
  { title: "Perfect form. Pure padel.", image: "/slider/img6.webp" },
  { title: "Speed meets control.", image: "/slider/img7.webp" },
  { title: "Strike clean. Move fast.", image: "/slider/img8.webp" },
  { title: "Sharp hits. Zero fear.", image: "/slider/img9.webp" },
  { title: "Focus locked. Game on.", image: "/slider/img10.webp" },
  { title: "Fluid motion. Strong finish.", image: "/slider/img11.webp" },
  { title: "Train smart. Play harder.", image: "/slider/img12.webp" },
  { title: "Instant reaction. Full power.", image: "/slider/img13.webp" },
  { title: "No limits. Just play.", image: "/slider/img14.webp" },
  { title: "Strike fast. Think fast.", image: "/slider/img15.webp" },
  { title: "Pure rhythm. Pure drive.", image: "/slider/img16.webp" },
  { title: "Every swing counts.", image: "/slider/img17.webp" },
  { title: "Push harder. Level up.", image: "/slider/img18.webp" },
  { title: "Stay sharp. Stay fierce.", image: "/slider/img19.webp" },
  { title: "Point by point. Win big.", image: "/slider/img20.webp" },
  { title: "Chase the rally. Own it.", image: "/slider/img21.webp" },
  { title: "Precision wins.", image: "/slider/img22.webp" },
  { title: "Elite focus. Elite energy.", image: "/slider/img23.webp" },
  { title: "Light swing. Heavy impact.", image: "/slider/img24.webp" },
  { title: "Play bold. Play clean.", image: "/slider/img25.webp" },
  { title: "Teamwork makes the point.", image: "/slider/img26.webp" },
  { title: "Quick read. Big return.", image: "/slider/img27.webp" },
  { title: "Pro movement. Pro mindset.", image: "/slider/img28.webp" },
];
